### PR TITLE
Added BatchWriteItem permission for dynamodb for entity deletion.

### PR DESCRIPTION
**Pull request by emmap321**

### CODE REVIEW

**Comment by emmap321** [comment]
Do you know why it says "Version": "2012-10-17"?

**Comment by jackwellsxyz** [comment]
LGTM!

**Review by RohitA5L — APPROVED** [review]
Can you also add this to the vpc branch

**Comment by saguziel** [comment]
the version thing is the AWS API version for the doc. pretty sure that's the latest version

**Comment by emmap321** [comment]
@RohitA5L I added it here https://github.com/tecton-ai-ext/tecton-terraform-setup/commit/8e807417fff63f79d7b2d9dbfb52956abc7ce557. Noticed that the emr spark policy is different than the master one.

**Pull request merged**
