### PR TITLE
chore: loosen up aws provider version contraints

### PR DESCRIPTION
**Pull request by zhoujoetan**
## What
Loosen up aws provider version constraints from ~> 3 to -> 4.60

## Why
To incorporate recent aws provider upgrade: https://github.com/tecton-ai/tecton/pull/14661 to support aws_kms_key_policy resource.

### CODE REVIEW

**Comment by zhoujoetan** [comment]
Current dependencies on/for this PR:
* master
  * **PR #109** <a href="https://app.graphite.dev/github/pr/tecton-ai-ext/tecton-terraform-setup/109" target="_blank">Graphite</a> 
    * **PR #111** <a href="https://app.graphite.dev/github/pr/tecton-ai-ext/tecton-terraform-setup/111" target="_blank">Graphite</a> 
    * **PR #110** <a href="https://app.graphite.dev/github/pr/tecton-ai-ext/tecton-terraform-setup/110" target="_blank">Graphite</a> 
      * **PR #108** <a href="https://app.graphite.dev/github/pr/tecton-ai-ext/tecton-terraform-setup/108" target="_blank">Graphite</a> 
        * **PR #107** <a href="https://app.graphite.dev/github/pr/tecton-ai-ext/tecton-terraform-setup/107" target="_blank">Graphite</a> 
          * **PR #112** <a href="https://app.graphite.dev/github/pr/tecton-ai-ext/tecton-terraform-setup/112" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/tecton-ai-ext/tecton-terraform-setup/112?utm_source=stack-comment).

**Comment by jakewhlr** [comment]
> Loosen up aws provider version constraints from ~> 3 to >= 3

Description needs updating I think ?

**Comment by zhoujoetan** [comment]
Good callout. Updated!

**Review by jakewhlr — DISMISSED** [review]

**Comment by zhoujoetan** [comment]
### Merge Activity

* **Sep 11, 7:26 PM**: @zhoujoetan started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/tecton-ai-ext/tecton-terraform-setup/112).

**Review by jakewhlr — APPROVED** [review]

**Pull request merged**
